### ISSUE TITLE
Free API alternative?

### ISSUE THREAD

**Issue by bmaioral** [retroflex/MMM-Fortnite#1]
Hi, thanks for making this module, does it stil work today?
I was trying to install it in my MM but I'm kinda lost with the USERNAME API I need because this one seems to be down:
https://fortnite-public-api.theapinetwork.com/prod09/users/id?username=YOURUSERNAME

Is there any other alternative?

Thanks so much in advance

**Comment by retroflex** [comment]
Very late reply, but I don't know. I'm not using the module anymore so I won't spend any time on it, but feel free to investigate.
