### ISSUE TITLE
MMM-Fortnite details are not showing

### ISSUE THREAD

**Issue by KiaSohc** [retroflex/MMM-Fortnite#2]
Hi there,

Hope all is well with you. I have just installed MMM-Fortnite but can't seem to make it work. Upon launching MM, all I can see for the Fortnite module is the "Loading..." status. I have already defined the required Fortnite userIDs but still does not display anything.

Below is the config I used...

		{
			module: 'MMM-Fortnite',
			header: 'Fortnite',
			position: 'top_center',
			config: {
				showScore: true,
				showMatchesPlayed: true,
				showKills: true,
				sortBy: 'kills',
				userIDs: [ 'xxxxx', 'xxxxx' ] //have deleted the actual ids for this sample
			}
		},

Would you have an idea whether I have missed to do anything?

Thanks in advance! :)

**Comment by retroflex** [comment]
It looks like the API is down. Not sure if there is another API. Since I don't use this module anymore I am not going to spend time on it, but feel free to research and make a pull request if you want.
